name: Lint dnbd3

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint dnbd3
    runs-on: ubuntu-22.04
    steps:
      - name: Install dnbd3 dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq make \
                                      clang-format \
                                      linux-headers-generic \
                                      libfuse-dev \
                                      libjansson-dev \
                                      rpm
      - name: Checkout dnbd3 repository
        uses: actions/checkout@v4
      - name: Fetch dnbd3 repository tags
        run: git fetch --prune --unshallow
      - name: Configure dnbd3 build
        run: |
          cmake -B ${{ github.workspace }}/build \
                -S ${{ github.workspace }} \
                -D DNBD3_BENCHMARK=ON
      - name: Lint dnbd3 artifacts
        working-directory: ${{ github.workspace }}/build
        run: make lint
